### DISCUSSION TITLE
Does config file support font fallback?

### DISCUSSION THREAD

**Discussion by johnchenkzy** [neovide/neovide#2306] [Q&A]
I look the document about config file [here](https://neovide.dev/config-file.html), but i can't find font fallback support in config file. Does config file support font fallback?

**Comment by al3xandru** [comment]
Could you use the `set guifont` as that allows configuring multiple fonts?

**Reply by johnchenkzy** [reply]
cause i want to use `[font.features]` , but `set guifont` can't set `font.features`, so i use `config file`,but `config file` seems can't set font fallback? here is my config file settings,but not working.
```toml
[font]
normal = ["MonoLisa Nerd Font", "fallback font"]
size = 18

[font.features]
MonoLisa = [ "+ss01", "+ss07", "+ss11", "-calt", "+ss09", "+ss02", "+ss14", "+ss16", "+ss17" ]
```
