### DISCUSSION TITLE
How can I remove this empty bar at the bottom below the lualine?

### DISCUSSION THREAD

**Discussion by hellovietduc** [neovide/neovide#2774] [Q&A]
I'm sorry if this question has been asked before but for the keywords that I have searched, I couldn't find any results. There is an empty bar below the lualine for me that doesn't appear when I run Neovim directly in the terminal.

![CleanShot 2024-08-26 at 10  20 34@2x](https://github.com/user-attachments/assets/dd228ecd-772d-441c-9b37-cd44345af743)

Here are my configurations:

```toml
frame = "transparent"
title-hidden = false
neovim-bin = "/opt/homebrew/bin/nvim"

# https://github.com/neovide/neovide/issues/2539#issuecomment-2214823903
# This says it's better to use a patched Nerd Font but I like using fallback
# because the icons are bigger.
# Docs: https://neovide.dev/config-file.html#font
[font]
normal = ["JetBrains Mono", "Symbols Nerd Font Mono"]
size = 15
```

```lua
-- font
vim.opt.linespace = 4 -- extra pixels per line

-- window
vim.opt.title = true -- show filename in the window title
vim.g.neovide_scale_factor = 1.0
vim.g.neovide_padding_top = 2
vim.g.neovide_padding_bottom = 0
vim.g.neovide_padding_right = 4
vim.g.neovide_padding_left = 4
vim.g.neovide_show_border = true

-- scroll animation
vim.g.neovide_scroll_animation_length = 0 -- some turning this off makes scrolling smoother
vim.g.neovide_scroll_animation_far_lines = 0 -- this prevents previews in fzf windows from snapping

-- cursor
vim.g.neovide_cursor_animation_length = 0.03
vim.g.neovide_cursor_trail_length = 0.4
vim.g.neovide_cursor_antialiasing = true
vim.g.neovide_cursor_animate_in_insert_mode = true
vim.g.neovide_cursor_smooth_blink = true
vim.o.guicursor = "n-v:block,i-c-ci-ve:ver25,r-cr:hor20,o:hor50,a:blinkwait700-blinkoff500-blinkon900-Cursor/lCursor"

-- input
vim.g.neovide_input_macos_option_key_is_meta = "only_left"
vim.g.neovide_input_ime = false
```

I'm using LazyVim 12.38.2.

Thanks everyone who's involved for making an amazing app. Without this I wouldn't have switched to Neovim completely because I can't bear the stuttered scrolling in the terminal.

**Comment by gsouf** [comment]
Same here, have you found a way around?

**Reply by gsouf** [reply]
fixed as explained here https://github.com/neovide/neovide/discussions/2774#discussioncomment-12992034

**Comment by fredizzimo** [comment]
You have to make sure that the window size is a multiple of the line height, otherwise there will be some padding.

I'm not sure which terminal you are using, but Wezterm, Alacritty and Kitty all renders black borders, while Neovide uses the background color

![image](https://github.com/user-attachments/assets/e3764f2e-d8cd-40f3-a9ee-5010bf251a49)

![image](https://github.com/user-attachments/assets/e973091e-247b-4bec-a204-545c8f35d6ec)

![image](https://github.com/user-attachments/assets/27fe7184-f3dd-4c3f-8a6e-667bdf5e16b6)

**Reply by fredizzimo** [reply]
Note this is with `cmdheight=1`, but the black border is there with zero.

Here's neovide without the border using `cmdheight=0`
![image](https://github.com/user-attachments/assets/e661f8ec-f8e8-4018-aab9-6259037006fe)


Note, there's a slight right border of one pixel, due fractional horizontal grid size.

Also, note that you can start Neovide with a fixed grid size by `neovide --grid 100x40`

**Reply by gsouf** [reply]
I was able to fix the issue by changing the font size in neovide config as explained here: https://neovide.dev/config-file.html#font  

```toml
[font]
normal = ['JetBrainsMono Nerd Font Propo']
size = 15
```

having a monitor of 1080 px in height, and using fullscreen unframed windows, it works well 👍🏽
