### ISSUE TITLE
Configure neovide in init.lua file

### ISSUE THREAD

**Issue by SabinAdkh** [neovide/neovide#1842]
I have already install astronvim in my laptop. I am using arch linux. After I install neovide in arch linux, when I open neovide it opens the file in a zoomed form. How do I disable that?. And If try to set it up in init.lua the option vim.g.neovide give error.

**Comment by fredizzimo** [comment]
Did you read the configuration guide? https://neovide.dev/configuration.html, what kind of error do you get?

**Comment by fredizzimo** [comment]
Closing this due to no response.

**Comment by SoaresAlisson** [comment]
The same problem here in Manjaro when installing Neovide via AUR.  It is possible to set the font size manually using something like `:lua vim.g.neovide_scale_factor=0.4` , changing the factor value as you wish; or make it persistent setting  `./.config/neovide/config.toml`. I commented some possible examples of fonts:

```toml
[font]
#normal = ["MonoLisa Nerd Font"]
#normal = ["haskell-mono-traversable"]
normal = ["MesloLGS NF"]
size = 8
```

See more on how to config https://neovide.dev/config-file.html.
