### ISSUE TITLE
Neovide isn't loading config.toml to set flags

### ISSUE THREAD

**Issue by reDpz** [neovide/neovide#1895]
**Describe the bug**
I have
```toml
multigrid = false
vsync = true
maximized = true
srgb = false
idle = true
neovim_bin = "C:\\Users\\nora\\AppData\\Local\\Programs\\Neovim\\bin\\nvim.exe"
frame = "none"
```
In `~\AppData\Roaming\neovide`

I also copied then pasted the folder into Local and Locallow just in case.

In my environment variables I have `XDG_CONFIG_HOME` set to `C:\Users\redpz\.config` so I decided to paste it into the config folder just in case it was sourcing it from there.

**Expected behavior**
It should load the config file and use `--frame none` without having to manually give it that flag

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Neovide Version 0.10.4
 - Neovim Version 0.9.1

Am I misplacing or incorrectly naming the folder?
