### ISSUE TITLE
Let users choose sRGB as their preferred color space

### ISSUE THREAD

**Issue by orlandosh** [neovide/neovide#2044]
**Is your feature request related to a problem? Please describe.**
Yes, on macOS we're used to themes that use the sRGB color space. So when migrating from kitty/alacritty/etc to Neovide our themes will look different. Colors will often look more vibrant, more vivid, which is unwanted is most cases.

**Describe the solution you'd like**
A setting like g:neovide_color_space = srgb

**Describe alternatives you've considered**
Honestly nothing else, changing themes isn't practical between sessions because it's much simpler to have just a single configuration, so it would only take getting used to the difference when using a terminal emulator vs neovide, though undesired. I personally also prefer sRGB.

**Additional context**
the following comments have screenshots and the full discussion is here: https://github.com/neovide/neovide/issues/1102#issuecomment-1726394535
https://github.com/neovide/neovide/issues/1102#issuecomment-1726596043

**Comment by Kethku** [comment]
This is already supported here https://neovide.dev/config-file.html. We can't have it in the neovim config as a variable because its required currently at window creation. In theory we could recreate the context when the setting changes, but thats not supported currently. Please reopen if this doesn't behave how you expect

**Comment by fredizzimo** [comment]
@Kethku, I'm re-opening this, that option is actually different. The option just requests a backbuffer with srgb support to work around some bugs with certain drivers, it does not really render in srgb, which is needed to look the same as terminal applications on macOS. Check the discussion in #1102 for more information.

**Comment by Kethku** [comment]
Ah my bad. Thanks for the catch

**Comment by fcaraujo** [comment]
Also interested in this topic.
Is it possible to configure this at the moment?

Also sharing here a screenshot for comparison [tested on macOS sonoma 14.6.1 (23G93)]- from the left is my neovide (with a floating term running lazygit), and on the right, the same conditions running on wezterm:

![image](https://github.com/user-attachments/assets/844f965a-05d3-4c3e-a8cb-152798786e0b)

**Comment by haxybaxy** [comment]
> Also interested in this topic. Is it possible to configure this at the moment?
> 
> Also sharing here a screenshot for comparison [tested on macOS sonoma 14.6.1 (23G93)]- from the left is my neovide (with a floating term running lazygit), and on the right, the same conditions running on wezterm:
> 
> ![image](https://github.com/user-attachments/assets/844f965a-05d3-4c3e-a8cb-152798786e0b)

I also had this issue, I just fixed it by manually setting the theme from .config/lazygit/config.yml 🎉

I'm using catppuccin so I just went to the official theme [here](https://github.com/catppuccin/lazygit) and copied the code below from the readme into the config.yml:

```yml
gui:
 # Use the mocha catppuccin theme
 theme:
   activeBorderColor:
     - '#89b4fa'
     - bold
   inactiveBorderColor:
     - '#a6adc8'
   optionsTextColor:
     - '#89b4fa'
   selectedLineBgColor:
     - '#313244'
   selectedRangeBgColor:
     - '#313244'
   cherryPickedCommitBgColor:
     - '#45475a'
   cherryPickedCommitFgColor:
     - '#89b4fa'
   unstagedChangesColor:
     - '#f38ba8'
   defaultFgColor:
     - '#cdd6f4'
   searchingActiveBorderColor:
     - '#f9e2af'

```
