### ISSUE TITLE
`title-hidden = true` in config file has no effect

### ISSUE THREAD

**Issue by emonadeo** [neovide/neovide#2342]
Setting `title-hidden = true` in the config file does not hide the title.
It works however when running neovide with `--title-hidden` flag.

### Config
`~/.config/neovide/config.toml`
```toml
frame = "buttonless"
title-hidden = true
```
### Command
```console
neovide
```
### Result
![image](https://github.com/neovide/neovide/assets/13782948/1eb3adb3-58e7-4fd6-865f-eb9c21545c9d)

### Config
`~/.config/neovide/config.toml`
```toml
frame = "buttonless"
```
### Command
```console
neovide --title-hidden
```
### Result
![image](https://github.com/neovide/neovide/assets/13782948/48f21c3e-55ab-4438-ac46-116040a2c8af)

## Expected behavior
The result of Exhibit A to match the result of Exhibit B

## Technical Details
 - OS: macOS 14.2.1
 - Neovide 0.12.2
 - NVIM 0.9.5

#### `~/.config/neovide/config.toml`
```toml
frame = "buttonless"
title-hidden = true

[font]
normal = "GeistMono Nerd Font Mono"
size = 16

[font.features]
"GeistMono Nerd Font Mono" = ["-liga"]
```

#### Neovide specific vim options
```
vim.g.neovide_cursor_vfx_mode = "railgun"
vim.g.neovide_cursor_vfx_particle_density = 14.0

vim.g.neovide_padding_top = 48
vim.g.neovide_padding_bottom = 48
vim.g.neovide_padding_right = 48
vim.g.neovide_padding_left = 48

vim.g.neovide_floating_blur_amount_x = 8.0
vim.g.neovide_floating_blur_amount_y = 8.0
vim.g.neovide_floating_shadow = false
```

### Log

[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/14176398/neovide_rCURRENT.log)
