### ISSUE TITLE
Cannot enable font features for CascadiaCode-Italic

### ISSUE THREAD

**Issue by mathletedev** [neovide/neovide#2474]
**Describe the bug**
When adding cursive option to `font.features`, text remains non-cursive

**To Reproduce**
`config.toml`:
```toml
[font]
normal = [ "Cascadia Code" ]
size = 16

[font.features]
# I have also tried CascadiaCode = [ "+ss01" ]
CascadiaCode-Italic = [ "+ss01"  ]
```

**Expected behavior**
Setting these options in the Kitty terminal
```
font_family Cascadia Code
font_size 12
font_features CascadiaCode-Italic +ss01
```
produces cursive when text is italic

**Screenshots**
Kitty + Neovim:
![image](https://github.com/neovide/neovide/assets/63214683/f8d14ef7-d742-4c0e-b1a7-25875acbe47b)

Neovide:
![image](https://github.com/neovide/neovide/assets/63214683/2286cb47-df6f-4ed4-933c-a66dac38d0f1)

**Desktop (please complete the following information):**
 - OS: NixOS 24.05
 - Neovide Version: 0.12.2
 - Neovim Version: 0.9.5

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
Log file too large, will attach if needed

**Additional context**

**Comment by iwinux** [comment]
This is working for me:

```toml
[font]
normal = ["Cascadia Code PL"]
size = 16

[font.features]
# simple compiler & simulator
# -> => != <> >= 0 1 2 3
"Cascadia Code PL" = ["+ss01", "+ss02", "+ss04", "+ss05", "+ss06", "+zero", "+onum"]
```

<img width="859" alt="image" src="https://github.com/neovide/neovide/assets/98864/7cd95763-a947-45b0-966e-a743be8dcc81">
