### ISSUE TITLE
Strange glyphs under Markdown headers

### ISSUE THREAD

**Issue by santoso-wijaya** [neovide/neovide#2536]
**Describe the bug**

There are strange glyphs under Markdown headers. They are messing with my line break perception. Even if I ignore the strange renders, they still take up a whole line visually while not actually being an empty line.

**To Reproduce**
1. Install Monaspace Nerd Font: `brew install --cask font-monaspace-nerd-font`
2. Set up NeoVide font in `config.toml` file:

```toml
[font]
normal = [
  "MonaspiceNe Nerd Font",
  "FiraCode Nerd Font",
  "Monaspace Neon",
  "Fira Code",
]
size = 12

[font.features]
MonaspiceNe = ["+calt", "+liga", "+dlig", "+ss01", "+ss02", "+ss03", "+ss04", "+ss05", "+ss06", "+ss07", "+ss08"]
Monaspace = ["+calt", "+liga", "+dlig", "+ss01", "+ss02", "+ss03", "+ss04", "+ss05", "+ss06", "+ss07", "+ss08"]
FiraCode = ["+cv01", "+cv03", "+cv11", "+onum", "+cv30", "+ss01", "+ss02", "+ss03", "+ss04", "+ss05", "+ss06", "+ss07"]
Fira = ["+cv01", "+cv03", "+cv11", "+onum", "+cv30", "+ss01", "+ss02", "+ss03", "+ss04", "+ss05", "+ss06", "+ss07"]
```

3. Open any Markdown file with a header.

**Expected behavior**
No visually empty lines--that aren't really there--under headers.

**Screenshots**
![Screenshot 2024-05-11 at 9 04 57 AM](https://github.com/neovide/neovide/assets/157527329/3ae16a85-7a7d-4a7a-a4bc-2539516fc374)

**Desktop (please complete the following information):**
 - OS: [e.g. macOS 11.4]
 - Neovide Version [e.g. 0.6.0]
 - Neovim Version [e.g. 0.5.0]

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

(attached below)

**Additional context**
I'm using Monaspace NerdFont
