### ISSUE TITLE
Input (typing) latency regression 0.12.2 -> 0.13.1

### ISSUE THREAD

**Issue by dimhatz** [neovide/neovide#2602]
First of all, thank you very much for this excellent neovim GUI! 

Measured on Windows 10, Ryzen 5600X, Radeon 5500XT 8GB, using typometer v1.1.0 from here: https://github.com/frarees/typometer/releases/tag/v1.1.0
(and oracle java 22 SE)

Command: `java --add-opens=java.desktop/java.awt=ALL-UNNAMED -jar typometer-1.1.0.jar`

Settings as shown in screenshot (chars was limited to 64 due to typometer unable to track further neovide v0.13.1, likely due to fonts being rendered differently). I took multiple measurements to compensate for less chars. 

Starting nvim (v0.10 stable) config:
```lua
vim.opt.number = true
vim.opt.mouse = 'a'
vim.opt.linespace = -1
vim.g.neovide_cursor_animate_in_insert_mode = false -- <-- to ensure minimal latency possible
```

Neovide config.toml:
```toml
size = 11 # <-- 11 for v0.13.1, 15 for v0.12.2
hinting = "full"
edging = "antialias"
normal = { family = "IosevkaCustom NF", style = "W350" } # 350 = SemiLight
bold = { family = "IosevkaCustom NF", style = "W600" } # 600 = Bold
italic = { family = "IosevkaCustom NF", style = "W350 Italic" }
bold_italic = { family = "IosevkaCustom NF", style = "W600 Italic" }
```

Font size was adjusted to make sure we have the same amount of text (lines) before running: 116 lines on my machine when maximized.

The initial nvim state is just a single blank buffer (see `fulltext` annotation below).

**Annotations on measurements**
`gl` -> used `--opengl` for v0.13.1
`dx` -> direct3d, did not use `--opengl` for v0.13.1
`fulltext` -> before taking measurements, the first 115 lines are filled with text (as opposed to a completely empty buffer otherwise), The last line (116) is empty and the cursor is placed there (in insert).

**TLDR / Findings**
With release 0.13.1 (and 0.13.0) the input latency is `>2x` vs 0.12.2.

d3d performs around 25% worse than opengl, at least on this machine. Additionally, with d3d there is some lag when scrolling, which comes and goes. During these laggy states, the gpu usage spikes ~35% -> ~55%. With opengl, gpu usage is stable at ~30% (when not idle).

When using `--no-vsync --no-idle` and ` vim.g.neovide_refresh_rate = 60`, with opengl, the latency improves by ~25%,
with d3d worsens 3x (!).

When using `--no-multigrid`, the latency improves across the board, but the best results are still with v0.12.2, when the screen is full
of text, see entries annotated with `fulltext`. With a completely empty buffer v0.12.2 and v0.13.1 opengl are the same.

![typometer](https://github.com/neovide/neovide/assets/7132507/1adccaad-b105-4132-8fb8-275604a6c9a5)
