### ISSUE TITLE
Font glyphs are not rendered clearly and consistently in v0.13.x (multiple fonts affected)

### ISSUE THREAD

**Issue by dimhatz** [neovide/neovide#2603]
Thanks again for this amazing nvim GUI!

In v0.13.x the font glyphs are not rendered as in v0.12. I cannot get the same clarity no matter the settings.

Also, the same glyph is rendered differently in different positions. AFAICT this affects most (all?) fonts (I provide screenshots for Source Code Pro, Fira, Iosevka).

I have tried different values for `vim.g.neovide_text_gamma`, `vim.g.neovide_text_contrast`, but it made no difference.

System: Windows 10, nvim 0.10 stable.

Neovide config:
```toml
[font]
size = 15 # 15 for v0.12.2, 11 - 11.4 for v0.13.1
hinting = "full"
edging = "antialias"
normal = { family = "Iosevka", style = "Light" } # the Extended, wider version, installed only these .ttfs
bold = { family = "Iosevka", style = "Bold" }
italic = { family = "Iosevka", style = "Light Italic" }
bold_italic = { family = "Iosevka", style = "Bold Italic" }


```
Sizes used: `15` for v0.12.2, `11 - 11.4` for v0.13.1. These give the same amount of lines, when neovide window is maximized.
Having tried basically all the fractions between `11 - 11.4`, none gives the desired result of v0.12.2. 

Iosevka is my main font. I use the `Extended`, wider version. It is the only Iosevka that I have installed on my system (all variants, Regular, Bold, Semibold etc), to ensure it is picked up correctly, not the default narrow version (in case anyone want to reproduce exactly).

Here are the screenshots. You may have to zoom in to see the differences.

Iosevka v0.13.1:
(even the clearest glyphs in the middle are not as clear as v0.12.2 rendering)
![iosevka-buggy](https://github.com/neovide/neovide/assets/7132507/0445c60a-11ff-41d4-ac9a-09f15a3e0ffb)

Iosevka v0.12.2:
![iosevka-ok](https://github.com/neovide/neovide/assets/7132507/c9ac7896-7abc-4f9f-abc5-8ecbed2bbada)

Fira v0.13.1:
![fira-buggy](https://github.com/neovide/neovide/assets/7132507/b5dbd778-68ce-46ab-93c5-b88dcbbb9a6e)

Fira v0.12.2:
![fira-ok](https://github.com/neovide/neovide/assets/7132507/eecdbd0e-ac9a-4a9a-bc43-3234bb85887e)

Source Code Pro v0.13.1:
![source-code-pro-buggy](https://github.com/neovide/neovide/assets/7132507/935b46b8-1942-4b65-88a5-4b717dd4031c)

Source Code Pro v0.12.2:
![source-code-pro-ok](https://github.com/neovide/neovide/assets/7132507/01649eac-2e8f-4fb8-aa12-85ba16c7b611)
