### ISSUE TITLE
Config file not working

### ISSUE THREAD

**Issue by Empathy117** [neovide/neovide#2632]
**Describe the bug**
I try to use this config file in `$HOME/.config/neovide/config.toml`
```toml
[font]
    normal = [] # Will use the bundled Fira Code Nerd Font by default
    size = 14.0

fork = false
frame = "buttonless"
idle = true
maximized = false
neovim-bin = "/usr/bin/nvim" # in reality found dynamically on $PATH if unset
no-multigrid = false
srgb = false
tabs = true
theme = "auto"
title-hidden = true
vsync = true
wsl = false
```
but it doesn't work, like if I set frame=buttonles on command line it will be buttonless, but on config file nothing happened. And I try to change other parameters, like font size but nothing happened either.

**To Reproduce**
1. run `brew install --cask neovide`
2. run `sudo launchctl config user path "$(brew --prefix)/bin:${PATH}"`
3. run `mkdir ~/.config/neovide/`
4. run `nvim ~/.config/neovide/config.toml` and paste the content of config
5. run `neovide`

**Desktop (please complete the following information):**
 - OS: [macOS 14.4.1]
 - Neovide Version [0.13.1]
 - Neovim Version [0.10.0]

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

[neovide_rCURRENT.log](https://github.com/user-attachments/files/15569765/neovide_rCURRENT.log)

**Comment by xzbdmw** [comment]
True, remove
```yaml
[font]
    normal = [] # Will use the bundled Fira Code Nerd Font by default
    size = 14.0
```
it works again

**Comment by fredizzimo** [comment]
It's just the documentation that's wrong, but it has not been merged yet due to problems with our CI. But until then, you can see the updated documentation here 
https://github.com/neovide/neovide/blob/969351f37e9e050bb78a2dfb0c58de3ead4597f9/website/docs/config-file.md

**Comment by aguynamedben** [comment]
This got me too on my first time trying Neovide, following the docs on the website.

@xzbdmw I think this is more of a TOML parsing bug. The TOML on the website IS valid, but doesn't work.

This is valid TOML per [this validator](https://www.toml-lint.com/) and partially works. With this setup, the [font] section seems to work, but the window settings below don't work.

```toml
[font]
    normal = ["Iosevka Nerd Font"]
    size = 12.0

frame = "none"
maximized = true
tabs = true
title-hidden = true
```

This is valid TOML and does work:

```toml
frame = "none"
maximized = true
tabs = true
title-hidden = true

[font]
    normal = ["Iosevka Nerd Font"]
    size = 12.0
```

This is with Neovide 13.1. It seems like if this can't be fixed, it should be more documented as a known bug in Neovide's TOML parsing, as both seem to be valid TOML from what I can tell.

BTW, Neovide is sick, thank you for working on it! 🙏
