### ISSUE TITLE
a few options for neovide/config.toml that would be very handy indeed

### ISSUE THREAD

**Issue by snoblenet** [neovide/neovide#2684]
I am looking for a clear way of ensuring that a single instance of the wonderful Neovide.app always functions as my one and only text editor.

I am thinking this could be achieved by adding the following configuration options and example configuration choices to neovide/config.toml:

```toml

# I am assuming the supported values for this option would be `true` or `false`, but
# you could imagine a later feature that supported a value like `allow_one_instance_workspace`.

allow_multiple_instances = false

# I am being naive about the syntax here. If TOML supports breaking these
# values across multiple lines, like YAML, then that would be even better.

nvim_flags = [ "-O", [ "--listen", "/tmp/NEOVIM_SOCKET" ] ]

source_vars = "~/.zshenv"

# The ZSH-style fallback value for $`NPM` here assumes that Neovide.app would evaluate
# the `source_vars` option before it evaluated the `set_vars` option.

set_vars = [ [ "PAGER", [ "nvim", "-R" ] ], [ "NPM", "${NPM:-/path/to/default/npm}" ] ]
```

I understand that many of the problems that this aims to solve can already be solved in other ways.

But those other methods are not simple and expressive, IMHO.

Thanks for such an awesome tool. I was astounded to find that when I moved from Kitty + nvim to Neovide.app, my editor actually became noticeably more responsive.

**Comment by snoblenet** [comment]
In fact, if Neovide.app evaluated `source_vars`, and then `set_vars` and then `nvim_flags`, the user could also do something like this:

```toml
nvim_flags = [ "-O", [ "--listen", "${NVIM_LISTEN_ADDRESS:-/tmp/NEOVIM_SOCKET}" ] ]
```

**Comment by snoblenet** [comment]
I should probably volunteer to help build this, but that would create the risk of me actually slowing development. I have deep experience with TypeScript, moderate experience with the Darwin/ZSH/etc shell environment, and zero experience with Rust. If there is a practical way I can contribute, do let me know.

**Comment by CGamesPlay** [comment]
Just want to offer a bit of commentary on this proposal. A few background notes:

- [TOML](https://toml.io/en/v1.1.0) does allow splitting arrays over multiple lines, and multiline strings.
- Environment variables and command-line arguments can only ever be strings, so it doesn't make sense to use an array to store their value.
- Environment variable substitution is possible to implement, but I would suggest that moving the environment variable setup into nvim itself is a better approach (which already exists), and can also be achieved by changing the nvim arguments.

So, my counter-proposal based on your example above would look like this:

```toml
# neovide/config.toml

reuse-instance = true # n.b. Renamed this based on the recent macos-only change

nvim-bin = [
    "nvim", "-O",
    # Use a single socket since we use a single neovide instance
    "--listen", "/tmp/NEOVIM_SOCKET"
]
```

Then, you can either do the environment variable setup in nvim's `init.lua`, or you could change the `nvim-bin` in a way that would set those variables:

```toml
# neovide/config.toml
nvim-bin = [ "zsh", "-c", """
. ~/.zshenv
export PAGER="nvim -R"
export NPM="${NPM:-/path/to/default/npm}"
nvim -O --listen /tmp/NEOVIM_SOCKET "$@"
""", "nvim-wrapper" ]
```
