### ISSUE TITLE
how to set italics as bold italic?

### ISSUE THREAD

**Issue by rafaeljacov** [neovide/neovide#2731]
![image](https://github.com/user-attachments/assets/00ca8087-08ec-4785-9483-d3aa510dec37)

**Comment by fredizzimo** [comment]
You can do that with the font config https://neovide.dev/config-file.html#font

For example
```toml
[[font.italic]]
family = "FiraCode Nerd Font"
style = "Bold Italic"
```
