### ISSUE TITLE
Neovide starts as a fullscreen all time

### ISSUE THREAD

**Issue by horanmustaplot** [neovide/neovide#2760]
**Describe the bug**
Neovide starts as a fullscreen all time, event if I set this in my `.config/neovide/config.toml` and  `vim.g.neovide_fullscreen = false` in my neovim configs if neovide.

**Expected behavior**
I simply want neovide to start as a normal window as others instead of taking the whole screen, like that:
![image](https://github.com/user-attachments/assets/6574a017-e202-42d1-a310-55974aa2f373)

**Screenshots**
I'm getting that when starting neovide
![image](https://github.com/user-attachments/assets/b01767a4-d670-43ca-8e01-613ab60632a2)

**Desktop (please complete the following information):**
 - OS: Arch Linux x86_64
 - Neovide Version [v0.10.1]
 - Neovim Version [0.11.2]

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
no logs provided
![image](https://github.com/user-attachments/assets/1bbc2db4-0ad0-4244-a168-dc9bc20bc810)

**Additional context**
I'm on wayland, and using hyprland
Also I don't think that neovide/config.toml file is loaded when neovide starts

the graph that provides some info about works but not the others
![image](https://github.com/user-attachments/assets/5e058d5b-23db-49c6-b961-3fa497c8268f)

result:
![image](https://github.com/user-attachments/assets/d2ea6b03-ab6a-4d2e-a62a-f10bf2e8e1c1)

`config.toml`
```toml
fork = false
frame = "none"
idle = true
maximized = false
neovim-bin = "/usr/bin/nvim" # in reality found dynamically on $PATH if unset
no-multigrid = false
srgb = false
tabs = true
theme = "auto"
title-hidden = true
vsync = true
wsl = false
```
