### ISSUE TITLE
Opening files in the current tab rather than in a new tab?

### ISSUE THREAD

**Issue by Oneechan69** [neovide/neovide#2820]
I would like to have all my open buffers in the same tab, when I double click to open a file in Neovide on macOS it opens in a new tab, even with `tabs = false` in my config. `~/.config/neovide/config.toml`, the other two settings work.

```toml
frame = "buttonless"
title-hidden = true
tabs = false
```
