### ISSUE TITLE
Specifying font family under [font] and automatically setting styles for bold, italic and bolt_italic

### ISSUE THREAD

**Issue by Oneechan69** [neovide/neovide#2887]
This would be a nice qol feature, to just specify a font and have Neovide automatically set all font styles, for instance something like this:

```toml
# specifying font family under font and omitting [[font.normal]] would have Neovide automatically setting font styles.
[font]
family = "CodeSaver Nerd Font"
size = 15.5
```

Rather than specifying all styles:

```toml
[font]
size = 15.5

[[font.normal]]
family = "CodeSaver Nerd Font"
style = "Medium"

[[font.bold]]
family = "CodeSaver Nerd Font"
style = "Bold"

[[font.italic]]
family = "CodeSaver Nerd Font"
style = "Medium Italic"

[[font.bold_italic]]
family = "CodeSaver Nerd Font"
style = "Bold Italic"
```
