### ISSUE TITLE
Setting multiple fonts and weights in config.toml?

### ISSUE THREAD

**Issue by Oneechan69** [neovide/neovide#2896]
I looked at this issue and tried setting a 2nd font under `font.normal` the but got an error:

```
TOML parse error at line 8, column 1
8 / [[font.normal]]
data did not match any variant of untagged enum FontDescriptionSettings
Continuing with default config.
```

```toml
frame = "buttonless"
title-hidden = true
tabs = false

[font]
size = 15.5

[[font.normal]]
family =[ "CodeSaver Nerd Font", "BabelStone Shapes"]
style = "Medium"

[[font.bold]]
family = "CodeSaver Nerd Font"
style = "Bold"

[[font.italic]]
family = "CodeSaver Nerd Font"
style = "Medium Italic"

[[font.bold_italic]]
family = "CodeSaver Nerd Font"
style = "Bold Italic"
```
